# -*- coding: utf-8 -*-
"""BM_25_fewshot selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xQ8YBg9Ypv_Z3mLo4Yl19CtMrw-gqcro
"""

!pip install rank_bm25 openpyxl

import pandas as pd
from rank_bm25 import BM25Okapi
import nltk
# Download the 'punkt_tab' data required for tokenization
nltk.download('punkt')
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize

# Load your Excel file
file_path = "/content/github_actions_failure_dataset_realistic.csv"  # Replace with the actual path if different
# The file path indicates a CSV file, so use pd.read_csv instead of pd.read_excel
df = pd.read_csv(file_path)

# Tokenize the failure logs for BM25
tokenized_logs = [word_tokenize(str(log).lower()) for log in df['log']]
bm25 = BM25Okapi(tokenized_logs)

def get_top_k_similar_examples(query, k=5):
    tokenized_query = word_tokenize(query.lower())
    scores = bm25.get_scores(tokenized_query)
    top_k_indices = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)[:k]
    return df.iloc[top_k_indices]

def format_example(log, cause, fix):
    return f"""Failure Log: {log}
Root Cause: {cause}
Suggested Fix: {fix}"""

def format_prompt(examples_df):
    return "\n\n".join(
        format_example(row['log'], row['explanation'], row['fix'])
        for _, row in examples_df.iterrows()
    )

query_log = """##[group]Run npm ci
npm ci
shell: /usr/bin/bash -e {0}
##[endgroup]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! While resolving: ttf-loader@1.0.2
npm ERR! Found: file-loader@4.3.0
npm ERR! Could not resolve dependency:
npm ERR! peer file-loader@"^1.1.6" from ttf-loader@1.0.2
npm ERR! Fix the upstream dependency conflict, or retry with --legacy-peer-deps.
##[error]Process completed with exit code 1."""
top_examples = get_top_k_similar_examples(query_log, k=5)
prompt_text = format_prompt(top_examples)
print(prompt_text)

